name: Update Docker Image

on:
  push:
    branches:
      - actions-test
  schedule:
    - cron: '05 01 * * *'

env:
  DOCKERHUB_USER: tomoyamachi
  DOCKERHUB_REPO: jq

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build a new image
        run: docker build . -t "${DOCKERHUB_USER}/${DOCKERHUB_REPO}:latest"
      - run: docker run --rm "${DOCKERHUB_USER}/${DOCKERHUB_REPO}:latest" --version
      - run: docker images

      - name: Login to Registries
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USER}" --password-stdin

      - name: Push to Docker Hub
        run: docker push "${DOCKERHUB_USER}/${DOCKERHUB_REPO}"